config/routes.rb
Momentz::Application.routes.draw do
  resources :status_updates
  resources :events
  root :to => "events#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get'signup', to: 'devise/registrations#new', as: 'signup'
    get'login', to: 'devise/sessions#new', as: 'login'
    get'logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  match "user_albums" => "users#fb_albums"
  match "get_picture" => "users#fb_picture"
  match "photos_by_album" => "users#fb_album"
  match "dev" => "events#anothershow"
  match "fb_friends" => "users#fb_friends"
  match "fb_friends_albums" => "users#fb_friends_albums"
  match "fb_share" => "events#fb_share"

end

app/models/status_update.rb
class StatusUpdate < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  attr_accessible :content, :location, :update_time, :fb_status_id, :event_id, :location, :poster, :message, :comments_count, :likes_count

  default_scope order('update_time DESC')

end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController
  # GET /status_updates
  # GET /status_updates.json
  def index
    @status_updates = StatusUpdate.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @status_updates }
    end
  end

  # GET /status_updates/1
  # GET /status_updates/1.json
  def show
    @status_update = StatusUpdate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status_update }
    end
  end

  # GET /status_updates/new
  # GET /status_updates/new.json
  def new
    @status_update = StatusUpdate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status_update }
    end
  end

  # GET /status_updates/1/edit
  def edit
    @status_update = StatusUpdate.find(params[:id])
  end

  # POST /status_updates
  # POST /status_updates.json
  def create
    @status_update = StatusUpdate.new(params[:status_update])

    respond_to do |format|
      if @status_update.save
        format.html { redirect_to @status_update, notice: 'Status update was successfully created.' }
        format.json { render json: @status_update, status: :created, location: @status_update }
      else
        format.html { render action: "new" }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /status_updates/1
  # PUT /status_updates/1.json
  def update
    @status_update = StatusUpdate.find(params[:id])

    respond_to do |format|
      if @status_update.update_attributes(params[:status_update])
        format.html { redirect_to @status_update, notice: 'Status update was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_updates/1
  # DELETE /status_updates/1.json
  def destroy
    @status_update = StatusUpdate.find(params[:id])
    @status_update.destroy

    respond_to do |format|
      format.html { redirect_to status_updates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/status_updates_helper.rb
module StatusUpdatesHelper
end

app/views/status_updates/_form.html.erb
<%= form_for(@status_update) do |f| %>
  <% if @status_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status_update.errors.count, "error") %> prohibited this status_update from being saved:</h2>

      <ul>
      <% @status_update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :update_time %><br />
    <%= f.datetime_select :update_time %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/status_updates/edit.html.erb
<h1>Editing status_update</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_update %> |
<%= link_to 'Back', status_updates_path %>

app/views/status_updates/index.html.erb
<h1>Listing status_updates</h1>

<table>
  <tr>
    <th>User</th>
    <th>Event</th>
    <th>Update time</th>
    <th>Location</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @status_updates.each do |status_update| %>
  <tr>
    <td><%= status_update.user %></td>
    <td><%= status_update.event %></td>
    <td><%= status_update.update_time %></td>
    <td><%= status_update.location %></td>
    <td><%= status_update.content %></td>
    <td><%= link_to 'Show', status_update %></td>
    <td><%= link_to 'Edit', edit_status_update_path(status_update) %></td>
    <td><%= link_to 'Destroy', status_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status update', new_status_update_path %>

app/views/status_updates/new.html.erb
<h1>New status_update</h1>

<%= render 'form' %>

<%= link_to 'Back', status_updates_path %>

app/views/status_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @status_update.user %>
</p>

<p>
  <b>Event:</b>
  <%= @status_update.event %>
</p>

<p>
  <b>Update time:</b>
  <%= @status_update.update_time %>
</p>

<p>
  <b>Location:</b>
  <%= @status_update.location %>
</p>

<p>
  <b>Content:</b>
  <%= @status_update.content %>
</p>


<%= link_to 'Edit', edit_status_update_path(@status_update) %> |
<%= link_to 'Back', status_updates_path %>