config/routes.rb
Momentz::Application.routes.draw do
  resources :status_updates
  resources :events
  root :to => "events#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get'signup', to: 'devise/registrations#new', as: 'signup'
    get'login', to: 'devise/sessions#new', as: 'login'
    get'logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  match "user_albums" => "users#fb_albums"
  match "get_picture" => "users#fb_picture"
  match "photos_by_album" => "users#fb_album"
  match "dev" => "events#anothershow"
  match "fb_friends" => "users#fb_friends"
  match "fb_friends_albums" => "users#fb_friends_albums"
  match "fb_share" => "events#fb_share"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :end_time, :privacy_status, :start_time, :title
  has_many :images
  has_many :musictracks
  has_many :events_users
  has_many :users, through: :events_users
  has_many :status_updates
  # after_save :create_statuses_for_event

def get_cover
  self.images.reverse.first
end

def create_statuses_for_event
  if start_time
    if start_time <= Time.zone.now
      if users.any?
        users.each do |user|
          if user.statuses.any?
            user.statuses.each do |status_update|
              if (StatusUpdate.where(:fb_status_id=>status_update['id'], :event_id=>id) == [])
                if (status_update['updated_time'] >= start_time) && (status_update['updated_time'] <= end_time)
                  #For each user, get their status updates between the times of the event 
                  new_status_update = user.status_updates.create(
                    :fb_status_id=>status_update['id'],
                    :poster=>status_update['from']['name'],
                    :message=>status_update['message'],
                    :update_time=>status_update['updated_time'],
                    :event_id=>id
                    )
                  if status_update['comments'] != nil
                    new_status_update.comments_count = status_update['comments']['data'].count
                    new_status_update.save
                  end
                  if status_update['likes'] != nil
                    new_status_update.likes_count = status_update['likes']['data'].count
                    new_status_update.save
                  end
                end
              end
            end 
           end
        end
      end
    end
  end
end
    # self.status_updates.destroy_all
    #May have to change the above to be this:
    #Booking.for_course(self.id).destroy_all
    # @thestatusupdates = []
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    if !current_user
      redirect_to login_url
    else
      @event = Event.new
      @musictracks = Musictrack.all
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @event }
      end
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new()
    @event.title = params['event']['title']

    if params['event']['musictrack']
      musictrack = @event.musictracks.build 
      musictrack.src = params['event']['musictrack']
    end

    # Put the photos for the event into the dB
    params['event']['photos'].each do |photo|
      photoobject = @event.images.build
      photoobject.fb_id = photo[1]["id"]
      photoobject.fb_created_time = photo[1]["created"]
      photoobject.height = photo[1]["height"]
      photoobject.width = photo[1]["width"]
      photoobject.source = photo[1]["source"]
      photoobject.from = photo[1]["from"]
      photoobject.fromid = photo[1]["fromid"]
      if photo[1]["cameFromSite"] == "Facebook"
        photoobject.name = photo[1]["name"]
        photoobject.frompic = current_user.get_profile_pic(photoobject.fromid)
        if photo[1]["comments"] 
          comments = photo[1]["comments"]["data"]
          comments.each do |comment|
            commentobject = photoobject.fbcomments.build
            commentobject.fb_created_time = comment[1]['created_time']
            commentobject.like_count = comment[1]['like_count']
            commentobject.user_likes = comment[1]['user_likes']
            commentobject.message = comment[1]['message']
            commentobject.from_name = comment[1]['from']['name']
            commentobject.from_id = comment[1]['from']['id']
            commentobject.picture = current_user.get_profile_pic(comment[1]['from']['id'])
        end #end each comment
      end #end if comments
      end #end if came came from Facebook
      if photo[1]["cameFromSite"] == "Instagram"
        photoobject.name = photo[1]["name"]["text"]
        photoobject.frompic = photo[1]["frompic"]
        if photo[1]["comments"]["count"] != "0"
          comments = photo[1]["comments"]["data"]
          comments.each do |comment|
            commentobject = photoobject.fbcomments.build
            commentobject.fb_created_time = comment[1]['created_time']
            # commentobject.like_count = comment[1]['like_count']
            # commentobject.user_likes = comment[1]['user_likes']
            commentobject.message = comment[1]['text']
            commentobject.from_name = comment[1]['from']['full_name']
            commentobject.from_id = comment[1]['from']['id']
            commentobject.picture = comment[1]['from']['profile_picture']
            commentobject.came_from_site = photo[1]["cameFromSite"]
          end #end each comment
        end #end if comments
      end
      

    end #end each photo


    # Set the event organiser
    @event.events_users.build(event: @event, user: current_user, user_type: "organiser")
    # TODO Then loop through the other users to assign them to the event also (although not as organisers)

    respond_to do |format|
      if @event.save
        # format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        # format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def fb_share
    current_user.facebook_details.put_wall_post("Check out this moflix!", {:link => request.referrer})
    respond_to do |format|
      format.json { head :no_content }
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container">
  <%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :start_time %><br />
      <%= f.datetime_select :start_time %>
    </div>
    <div class="field">
      <%= f.label :end_time %><br />
      <%= f.datetime_select :end_time %>
    </div>

  <!--   <div class="field">
      <p>Select User</p><br />
    </div> -->

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container mf_container">
  
  <h1>Featured Moflix</h1>

    <div class="row">
      <div id="gallery">
        <ul>
          <% @events.reverse.each do |event| %>
            <% if event.get_cover %>
              <% if event.get_cover.source != nil %>
                <% calculation = event.get_cover.width.to_f / 275 %>
                  <li>
                    <div class="gal_image">
                      <img src="<%=event.get_cover.source %>" width="275" height="<%= (event.get_cover.height.to_f) / calculation %>">
                      <div class="hoverimage"><a href="<%= event_path(event) %>
                        " class="play_button"><i class="fa fa-youtube-play play_button"></i></a></div>
                    </div>
                    <div class="text_section">
                      <div class="media">
                        <a class="pull-left" href="#">
                          <img class="gal-user-profile" src="
                          <% if event.users.first.image %>
                            <%= event.users.first.image %>
                          <% else %>
                            <!-- Put code for anonymous user image here -->
                          <% end %>
                          " width="35" height="35">
                        </a>
                        <div class="media-body">
                          <h4 class="media-heading">
                            <% if event.title %>
                              <%= truncate(event.title, length: 30) %>
                            <% else %>
                              Just another moflix
                            <% end %>
                          </h4>
                          by 
                          <% if event.users.first.name %>
                            <%= event.users.first.name %>
                          <% else %>
                            an anonymous user
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </li>
            <% end %>
            <% end %>
          <% end %>

      </ul>
    </div>
  <div class="clearfix">
</div>

<script>
$(function() {
  
  $('#gallery li').wookmark({
    autoResize: true, // This will auto-update the layout when the browser window is resized.
    container: $('#gallery'), // Optional, used for some extra CSS styling
    offset: 13, // Optional, the distance between grid items
    itemWidth: 280 // Optional, the width of a grid item
  })
  
})

</script>