config/routes.rb
Momentz::Application.routes.draw do
  resources :status_updates
  resources :events
  root :to => "events#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get'signup', to: 'devise/registrations#new', as: 'signup'
    get'login', to: 'devise/sessions#new', as: 'login'
    get'logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  match "user_albums" => "users#fb_albums"
  match "get_picture" => "users#fb_picture"
  match "photos_by_album" => "users#fb_album"
  match "dev" => "events#anothershow"
  match "fb_friends" => "users#fb_friends"
  match "fb_friends_albums" => "users#fb_friends_albums"
  match "fb_share" => "events#fb_share"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moflix</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
  <!-- font for moflix logo -->
  <link href='http://fonts.googleapis.com/css?family=Slackey' rel='stylesheet' type='text/css'>
  <!-- fonts for slidehow -->
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300' rel='stylesheet' type='text/css'>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <% if request.path_parameters[:controller] == "events" && request.path_parameters[:action] == "show" %>
    <% event_for_FB = Event.find(request.path_parameters[:id]) %>
    <meta property="og:title" content="<%= event_for_FB.title %>" />
    <meta property="og:site_name" content="Moflix"/>
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="fb:app_id" content="212771185582572" />
    <meta property="og:image" content="<%= event_for_FB.images.reverse.first.source %>" />
  <% end %>

  
</head>
<body>
  <div class="mf-bg">
</div>

  <div class="navbar transparent navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>"><span class="moflix">moflix</span></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="<%= events_path %>">Gallery</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <form action="<%= new_event_path %>">
                  <button class="btn mf_btn navbar-btn"><span class="glyphicon glyphicon-film"></span> Create a moflix</button>
              </form>
            </li>
          <% if current_user %>
            <li><a>Signed in 
              <% if ( current_user.name != "" ) %> 
                as <%= current_user.name %>
              <% end %></a></li>
            <li><a href="<%= logout_path %>">Logout</a></li>
          <% else %>
            <li><a href="<%= login_path %>">Login</a></li>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
<%= yield %>
</body>
</html>